steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'asia-south1-docker.pkg.dev/fastapi-test/custom-fastapi/custom-fastapi:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/fastapi-test/custom-fastapi/custom-fastapi:latest']
    waitFor: ['-']
