FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /code

# Install dependencies for running your app (including curl and git)
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg curl

# Copy the requirements.txt to the container
COPY req.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r req.txt

# Copy the src directory into the container
COPY src /code/src

# Set the PYTHONPATH environment variable to point to the src directory
ENV PYTHONPATH=/code/src

# Expose the default port (8080 for Cloud Run)
EXPOSE 8080

# Set the command to run the app with uvicorn on port 8080
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]